# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author:
  name: Akhil Tiwari
  email: akhiltiwari.13@gmail.com  # Add this line
  bio: >-
    Trading systems engineer with 10+ years of expertise in HFT,
    low-latency infrastructure, and distributed platforms.
  github: akhiltiwari13
  linkedin: akhiltiwari-13
# title: Akhil Tiwari | HFT & Trading-Systems' Engineer
# email: akhiltiwari.13@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   High-frequency trading systems' engineer specialiaing in low-latency C++ implementations, exchange connectivity, and performance-critical trading infrastructure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akhiltiwari13.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  akhiltiwari13

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  services:
    output: true
    permalink: /services/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

sass:
  sass_dir: _sass
  style: compressed

# Custom variables
author:
  name: Akhil Tiwari
  bio: >-
    Trading systems engineer with 10+ years of expertise in HFT,
    low-latency infrastructure, and distributed platforms.
  github: akhiltiwari13
  linkedin: akhiltiwari-13

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
